# llm_router.spec
# PyInstaller spec — 单文件 exe 打包
# 用法: pyinstaller llm_router.spec --clean --noconfirm

# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'nicegui',
        'nicegui.cli',
        'nicegui.observables',
        'nicegui.elements',
        'nicegui.binding',
        'nicegui.page',
        'nicegui.context',
        'nicegui.dataclasses',
        'nicegui.app',
        'nicegui.client',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'pystray',
        'pystray._win32',
        'aiosqlite',
        'yaml',
        'cryptography',
        'jsonschema',
        'aiohttp',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'asyncio',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.staticfiles',
        'fastapi',
        'fastapi.middleware',
        'httpcore',
        'httpx',
        'anyio',
        'websockets',
        'watchfiles',
        'python_multipart',
        'orjson',
        'docutils',
        'markdown2',
        'aiofiles',
        'socketio',
        'engineio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'torch',
        'tensorflow',
        'pywebview',
        'bottle',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='llm_router',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
